### ISSUE TITLE
Install web application from a git

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#10]
A web application in now installed from [.tar file](https://github.com/CSIRT-MU/Stream4Flow/blob/master/provisioning/ansible/roles/web/files/Stream4Flow.tgz) in [task install](https://github.com/CSIRT-MU/Stream4Flow/blob/master/provisioning/ansible/roles/web/tasks/install_webapp.yml) in web role.

This should be installed directly from the git repository.

- [x] Explore, how current web installation is done
- [x] Create a new git branch for development of a new installation
- [x] Develop a new installation directly from a repository folder [web application](https://github.com/CSIRT-MU/Stream4Flow/tree/master/web-interface) 
- [x] Add dynamic hostname configuration during installation process

**Comment by tomjirsa** [comment]
- [ ] Add dynamic hostname configuration for a host

**Comment by simkosvorad** [comment]
Everything is set, currently not working probably because file attributes are not set properly.

**Comment by simkosvorad** [comment]
Everything works as intended.

**Comment by tomjirsa** [comment]
After attempt to login to web portal, following error occurs:
```
Traceback (most recent call last):
  File "/var/www/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/var/www/web2py/applications/Stream4Flow/controllers/default.py", line 155, in <module>
  File "/var/www/web2py/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/var/www/web2py/applications/Stream4Flow/controllers/default.py", line 60, in login
    db(db.users_logins.user_id == session.user_id).update(last_login=datetime.now())
  File "/var/www/web2py/gluon/packages/dal/pydal/objects.py", line 2054, in update
    ret = db._adapter.update("%s" % table._tablename, self.query, fields)
  File "/var/www/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1031, in update
    raise e
OperationalError: unable to open database file
```

Probably wrong settings of user rights - all in web files needs to have following user rights : user: www-data, group: www-data

**Comment by tomjirsa** [comment]
Seems we need to use `recurse: yes` in [install_web](https://github.com/CSIRT-MU/Stream4Flow/blob/web-installation/provisioning/ansible/roles/web/tasks/install_webapp.yml) file. 

viz. [stackoverflow](http://stackoverflow.com/questions/28778738/ansible-mode-755-for-directories-and-644-for-files-recursively)

```xml
- name: Set application attributes
  file:
     path: /var/www/web2py/applications/Stream4Flow
     owner: www-data
     group: www-data
```

**Comment by tomjirsa** [comment]
Fixed, merged with master. #17
