### ISSUE TITLE
Stream4Flow README 

### ISSUE THREAD

**Issue by simkosvorad** [CSIRT-MU/Stream4Flow#11]
I would recommend adding description of solution to the problem when ansible is not installed before using `$ vagrant up` which is installing ansible and then using `$ vagrant provision consumer`.

Also the command `softflowd -i <your interface> -n 192.168.0.2:4739` didn't work for me, using the command in debug mode as `softflowd -i <your interface> -D -n 192.168.0.2:4739` seemed to solve the problem.

**Comment by tomjirsa** [comment]
Thanks for pointing out. Readme updated in 3190614775e002ab7f5581bae10ced0e7f38f9cb

**Comment by simkosvorad** [comment]
I think there is a typo in sentence 

> Note: machines in cluster must run Debian OS ekvivalent to Ubuntu 14.* (due to initd)

I believe it should be spelled " equivalent ".
