### ISSUE TITLE
Update to latest ELK

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#14]
Update to latest stable Elastic 5.2.1

- [x] Udate to latest Elastic - check elasticdsl queries in web interface
- [x] Update to latest Logstash 
- [x] Update to latest Kibana

**Comment by tomjirsa** [comment]
Note: create new branch from **master**

**Comment by simkosvorad** [comment]
Update required adding RAM to consumer, because elasticsearch needs to allocate 2GB of RAM.

**Comment by tomjirsa** [comment]
Ok, agree, please update the vagrant file and the README file (Requirements) accordingly.

**Comment by tomjirsa** [comment]
Found error during deployment:
```
TASK [elk : Restart Elasticsearch] *********************************************
fatal: [consumer]: FAILED! => {"changed": false, "failed": true, "msg": " * Stopping Elasticsearch Server\n   ...done.\n * Starting Elasticsearch Server\n[2017-03-13T10:33:45,317][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/etc/elasticsearch/logging.yml], logging is configured via [/etc/elasticsearch/log4j2.properties]\n   ...fail!\n"}
```
Please fix it

**Comment by tomjirsa** [comment]
fixed, closed
