### ISSUE TITLE
Ansible - Tcp normalizer

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#16]
During Instalation from vagrant+ansible in ubuntu 16.04 following error occurs:

RUNNING HANDLER [ubuntu-systemd-normalizer : Restart Service Instance 'default'] ***
fatal: [producer]: FAILED! => {"changed": true, "cmd": ["systemctl", "restart", "tcpnormalizer@default.service"], "delta": "0:00:00.075229", "end": "2017-02-24 09:02:06.997307", "failed": true, "rc": 1, "start": "2017-02-24 09:02:06.922078", "stderr": "Failed to restart tcpnormalizer@default.service: Interactive authentication required.\nSee system logs and 'systemctl status tcpnormalizer@default.service' for details.", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/data/Stream4Flow/provisioning/ansible/site.retry

Linked issues: #15

**Comment by xdanos** [comment]
Fixed in af8774278f473f254cedebb1170e23a7d1b6a62e
