### ISSUE TITLE
Basic integration test

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#21]
Create a basic integration test

1. Think of mechanism for integration tests, repository structure, etc.
2. Create new branch with integration test
3. The basic test should test, whether the whole workflow works. Test steps:
   - [ ] copy test data
   - [ ] run application protocol statistics
   - [ ] run ipfixsend to send test data
   - [ ] query elasticsearch for stored data
   - [ ] check the correcntess measured data (the number of flows match)

Adding @xdanos  and @cermmik  to follow.

**Comment by simkosvorad** [comment]
Web interface contains example of connection to elastic in python /web-interface/Stream4Flow/controllers/protocols-statistics.py

**Comment by simkosvorad** [comment]
http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html

**Comment by simkosvorad** [comment]
Integration test seems to be working, I need to try it on clean start of cluster to see if all dependencies are installed during deployment. Test is not querying elasticsearch for data but reading it as a json from webpage, for easier excluding the number of flows. The test now (hopefully) works only when there are no indices in elasticsearch before running the test. 
The script for finding the number of flows measured by elastichsearch is [here](https://github.com/CSIRT-MU/Stream4Flow/blob/integration-test/provisioning/ansible/roles/integration-test/files/query_for_data.py).
For executing the test you need to in `~/Stream4Flow/provisioning/test/integration` directory and test is ran by `ansible-playbook integration-test.yml -i inventory.ini.example -U spark --ask-pass` command.

**Comment by simkosvorad** [comment]
Integration test is stored in [~/Stream4Flow/provisioning/test/integration-test](url).

**Comment by tomjirsa** [comment]
Closing, merged in #39
