### ISSUE TITLE
Application automatic install

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#22]
Add to ansible automatic installation of applications from [github repository folder](https://github.com/CSIRT-MU/Stream4Flow/tree/master/applications).

**Comment by tomjirsa** [comment]
Need to sync with @severinsimko  and issue #18 due to import existing applications to the web database.

**Comment by simkosvorad** [comment]
Paths to applications with default settings are:
/home/spark/applications/protocol-statistics/protocol_statistics.py
/home/spark/applications/host-statistics/host_statistics.py
/home/spark/applications/detection-ddos/detection_ddos.py
/home/spark/applications/reflect-ddos/reflectdos_main.py

**Comment by tomjirsa** [comment]
Closing by merge #35
