### ISSUE TITLE
Spark Optimization

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#28]
- Optimize parameters for [run-application.sh](https://github.com/CSIRT-MU/Stream4Flow/blob/master/provisioning/ansible/roles/spark/templates/run-application.sh.j2)
- Use spark native configuration
- Tune logging settings

**Comment by tomjirsa** [comment]
Check logging options, consult their relevancy with @cermmik 
If suitable, move them to spark default config.

**Comment by cermmik** [comment]
Will be updated within dynamic resource allocation.
