### ISSUE TITLE
Change IP mapping in logstash from IPv4 to IP

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#32]
- [ ] Change mapping in logstash
- [ ] Change send format in applications

**Comment by tomaspvk** [comment]
Changed in branch output-to-kafka
send format changed in ddos detection applications
mapping template changed, e.g.: dst_ipv4  => dst_ip
added dns_ip as type ip

**Comment by tomjirsa** [comment]
Merged in #49
