### ISSUE TITLE
Add proxy support for mvn

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#33]
Add proxy support for mvn [tutorial](https://maven.apache.org/guides/mini/guide-proxies.html)
* there should be a boolean global variable, whether turn the proxy support on. 
* additional parameters from proxy settings should be also as variables
* check for variables if filled in
* part of role common task install java

**Comment by simkosvorad** [comment]
Proxy support is enabled by `maven_proxy` variable, by default set to False, other proxy variables are by default set to "not_set", it is needed to set every variable for proxy to be enabled.

**Comment by tomjirsa** [comment]
Merged with master by #40. Closing
