### ISSUE TITLE
Install IPFIXcol with all plugins

### ISSUE THREAD

**Issue by cermmik** [CSIRT-MU/Stream4Flow#36]
During provisioning build all IPFIXcol plugins (especially fastbit) to allow better development and testing of analytical applications.

**Comment by tomaspvk** [comment]
Added fastbit, nfdump, postgres and statistics storage plugins to the provisioning with necessary dependencies.

**Comment by tomjirsa** [comment]
Please add tool fbitdump for data browsing - #55 
Github
- https://github.com/CESNET/ipfixcol/tree/master/tools/fbitdump

Ansible
- https://github.com/CESNET/ipfixcol/blob/master/ansible/roles/ipfixcol/tasks/tools.yml

**Comment by tomjirsa** [comment]
Merged by #55 , closing.
