### ISSUE TITLE
Update the consumer to read data directly from Kafka

### ISSUE THREAD

**Issue by cermmik** [CSIRT-MU/Stream4Flow#45]
Update configuration of the Logstash on the consumer to read data directly from Kafka.

- [x] Create output topic in the Kafka.
- [x] Update Logstash configuration to read data from both socket and Kafka.
- [x] Update current applications so they will send data not to the port but to the given Kafka topic.
- [x] Check performance of the solution (multiple applications sending data to one topic).
- [x] Add all necessary steps to the provisioning.
- [x] Update documentation of the Stream4Flow (also change the arrow pointing from Spark to an arrow pointing from Kafka).

**Comment by tomjirsa** [comment]
Adding @tomjirsa to follow

**Comment by tomaspvk** [comment]
Created topic, updated logstash config, tested functionality of solution for ssh_auth_simple application

**Comment by tomaspvk** [comment]
Updated all other applications, updated ansible (not tested yet) and part of the documentation. Checked performance while running 4 applications simultaneously (all records from output were almost immediately visible in kibana)

**Comment by cermmik** [comment]
Please create and push a new GIT branch related to this topic with all these changes.

**Comment by tomaspvk** [comment]
Final commit + merge request

**Comment by tomjirsa** [comment]
Tested, merged by #49
