### ISSUE TITLE
Prepare template for new applications

### ISSUE THREAD

**Issue by cermmik** [CSIRT-MU/Stream4Flow#57]
Added missing issue for the "applications-template" branch.

- add missing documentation and comments
- add new lines to the end of scripts
- move send_data_to_kafka function before spark_start
- set microbatch value in variable within main

**Comment by tomaspvk** [comment]
Fixed mentioned issues in the latest commit

**Comment by cermmik** [comment]
So, is it ready for a merge?

**Comment by cermmik** [comment]
Merged :)
