### ISSUE TITLE
Web app to elastic connection

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#6]
Can be elasticsarch connection set automatically, according to deploymnet? 

During usage on openstack cluster, following error occured:

Error: Elasticsearch query exception: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5674103150>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5674103150>: Failed to establish a new connection: [Errno -2] Name or service not known)

**Comment by cermmik** [comment]
Check if hostnames ("consumer", ...) on the web server are correct.

**Comment by tomjirsa** [comment]
Hostname/ip of a machine with ipfix: sec-cloud-producer 192.168.0.5
Inventory file of ansible: producer 192.168.0.5
/etc/hosts on machine with ipfix: producer 192.168.0.5

- With this settings kafka wont start - the name of the machine in ansible inventory file must match the hostmame of the machine. 

During the github deployment of the web a hostname can not be static but must be changen in webapp accrodingly to the inventory file (= real host name)

**Comment by tomjirsa** [comment]
Dynamic hostnames configuration in web will be added during the web installation in CSIRT-MU/Stream4Flow/issues/10
