### ISSUE TITLE
Migrate to ansible 2.2+  with python 3 support

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#7]
Try to migrate ansible to python3 - 

https://docs.ansible.com/ansible/python_3_support.html

**Comment by tomjirsa** [comment]
@jpaulovic - I know, that you are working with ansible. Do you happen to know, when a stable version of ansible with python 3 support is about to come?

**Comment by jpaulovic** [comment]
As you can see from the official site, Python3 support is in active development and will only be getting bigger. No official dates yet, though.

**Comment by cermmik** [comment]
Closing the issue due to development workload.
