### ISSUE TITLE
spark-2.1.1 does not exist

### ISSUE THREAD

**Issue by ChandanY1011** [CSIRT-MU/Stream4Flow#71]
Error 404: http://apache.miloslavbrada.cz/spark/spark-2.1.1/spark-2.1.1-bin-hadoop2.7.tgz

The directory http://apache.miloslavbrada.cz/spark/spark-2.1.1 does not exist on the server anymore. One gets Error 404 while installing.

**Comment by cermmik** [comment]
The Stream4Flow configuration uses the mirror of the Apache Spark that is nearest to us. However, it seems that this resource does not keep older versions. You can use a mirror that is nearest to you (use link from <http://spark.apache.org/downloads.html>) or change the address in the configuration to <https://archive.apache.org/dist/spark/spark-2.1.1/spark-2.1.1-bin-hadoop2.7.tgz>.

We will set this original source as the default configuration option.

**Comment by tomjirsa** [comment]
Mirror URL has been updated to proposed link in commit f98e7e7 
Closing
