### ISSUE TITLE
Enable dynamic allocation of the Spark resources

### ISSUE THREAD

**Issue by cermmik** [CSIRT-MU/Stream4Flow#73]
Set `spark.streaming.dynamicAllocation.enabled=true` in the run_application.sh to allow Spark decide the correct number of resources.

To enable dynamic allocation it is necessary to modify the microbatch size to fit the window size for all applications.

**Comment by cermmik** [comment]
Created branch dynamic-resourcess-allocation to update all applications.

**Comment by tomjirsa** [comment]
merged in #79.  Closing
