### ISSUE TITLE
Copy we2py fails in second run

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#77]
ansible fails in second run for task web: Copy Stream4Flow we2py application

```
Copy Stream4Flow web2py application] *******************************
fatal: [consumer]: FAILED! => {"changed": true, "cmd": ["mv", "/tmp/Stream4Flow/web-interface/Stream4Flow", "/var/www/web2py/applications/"], "delta": "0:00:00.001978", "end": "2017-11-02 15:13:06.419469", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-02 15:13:06.417491", "stderr": "mv: cannot move '/tmp/Stream4Flow/web-interface/Stream4Flow' to '/var/www/web2py/applications/Stream4Flow': Directory not empty", "stderr_lines": ["mv: cannot move '/tmp/Stream4Flow/web-interface/Stream4Flow' to '/var/www/web2py/applications/Stream4Flow': Directory not empty"], "stdout": "", "stdout_lines": []}
```

**Comment by cermmik** [comment]
Resolved in a2a4b6e52885504b2f6429f6ad292f777baef3c1

**Comment by ChandanY1011** [comment]
Is it okay to delete the contents of this directory (/var/www/web2py/applications/Stream4Flow/) by ssh-ing into consumer and then run 'vagrant provision' again?

**Comment by tomjirsa** [comment]
you can delete the directory /var/www/web2py/applications/Stream4Flow/. Instead of running again vagrant provision, just scp the folder from git dir Stream4Flow/web-interface/Stream4Flow/ to consumer dir /var/www/web2py/applications/Stream4Flow/.
