### ISSUE TITLE
Include - Simple TCP Normalizer 

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#8]
Include simple [TCP normalizer](https://github.com/CSIRT-MU/simple_tcp_normalizer) into deployment process

- create a new branch 
- in this branch replace logstash on a producer for simple TCP normalizer in ansible deployment

**Comment by xdanos** [comment]
Depends on #5 since Ubuntu 16.04 is needed.

**Comment by xdanos** [comment]
Commit 3e9ed7ffe7f363650f271629bea519ea04fd86eb
