### ISSUE TITLE
Ansible variables in configuration file

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#9]
Goal is to aggregate all variables from ansible provisioning into one configuration file to make the deployment easier and more configurable.

- [x] Explore possibilities and chose a few
- [x] For a chosen possibility device a minimalistic example ansible playbook
- [x] Present examples and choose final solution
- [x] Create a branch for solution application
- [ ] Apply solution to an ansible provisioning folder

**Comment by simkosvorad** [comment]
I found 3 possibilities which were` include_vars` in tasks, `vars_files` in playbooks and group_vars. We chose group_vars possibility because it doesn't require any modification of roles or playbooks.

**Comment by tomjirsa** [comment]
Done, merged with master in #12
