### ISSUE TITLE
Not able to run vagrant provision commandn and gettig this error

### ISSUE THREAD

**Issue by kullu208025** [CSIRT-MU/Stream4Flow#91]
![screenshot from 2018-11-27 02-15-06](https://user-images.githubusercontent.com/26632404/49009589-f4d83a80-f196-11e8-9f99-7259c2cb373f.png)

**Comment by tomjirsa** [comment]
Hi, 
the apt-cache update failed. You can try to run apt-cache update directly on the machine to see details of the error. 
From here it seems that your machine does not have access to the Internet.
