### ISSUE TITLE
Cam we save the data for later analysis

### ISSUE THREAD

**Issue by akhilgupta0221** [CSIRT-MU/Stream4Flow#93]
Hi 

Can I use this project for saving the data in HDFS for later analysis if not then can you point me to other popular project.

Regards
Akhil

**Comment by cermmik** [comment]
Hello,
our project is focused on the stream-based analysis. Therefore, we do not have any connector to the HDFS. 

Analysis flows in HDFS is really hard task (and HDFS isn't a good choice for such a scenario). However, you can check project [SecurityCloud](https://github.com/CESNET/SecurityCloud/wiki) which was developed as well as Stream4Flow but is focused on batch-based analysis and uses GlusterFS.

**Comment by akhilgupta0221** [comment]
@cermmik : Thanks !!!
