### ISSUE TITLE
Can I use this project for marketing related data for customer segmentation

### ISSUE THREAD

**Issue by akhilgupta0221** [CSIRT-MU/Stream4Flow#94]
Hi 

Can I use this project for the marketing related data for customer segmentation.

I needed it for live streaming as well as for the batch processing (for storage and use it for the later analysis).

OR
 
Point me to some other projects on github.

Any help will be appreciated 

Regards
Akhil

**Comment by cermmik** [comment]
This project is focused on IP Flow data analysis (network traffic related data). You can use its parts (e.g. Kafka-Spark-Elk) but we are not focused on such tasks like marketing data processing. Currently, you can find many existing solutions fot marketing data processing and we do not have a full overview about them.
