### ISSUE TITLE
issue raises when running vagrant up

### ISSUE THREAD

**Issue by ziyiy** [CSIRT-MU/Stream4Flow#99]
Hi I was trying to run Standalone deployment. After running vagrant provisioning, I met some issues. Can you help me to check about that?

![image](https://user-images.githubusercontent.com/5078779/63075794-e4bce280-bf00-11e9-8927-21ccec08c645.png)

Vagrant version: Vagrant 2.2.5
Ansible version: ansible 2.8.3

**Comment by cermmik** [comment]
Hi, I just updated the provisioning and resolved several bugs (including yours). Everything should be working now.
